name: Go CI with Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Download Dependencies
        run: go mod download

      - name: Format Check
        run: test -z "$(gofmt -s -l .)"

      - name: Lint (staticcheck)
        uses: dominikh/staticcheck-action@v1

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
